version: '3'

services:
  oncall-web:
    build: .
    hostname: oncall
    ports:
      - "8080:8080"
      - "8001:8001"
    environment:
      - DOCKER_DB_BOOTSTRAP=1
      - IRIS_API_HOST=iris
    volumes:
      - ./configs/config.docker.yaml:/home/oncall/config/config.yaml
    networks:
      - iris

  oncall-mysql:
    hostname: oncall-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - iris

  prometheus-oncall:
    hostname: prometheus-oncall
    image: prom/prometheus
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./configs/blackbox_targets:/etc/prometheus/blackbox/targets
    ports:
      - 9090:9090
    networks:
      - iris

  shift-oncall-exporter:
    # build: ./src/shift_exporter
    image: shift-oncall-exporter:latest
    hostname: shifts-oncall-exporter
    ports:
      - 8002:8002
    networks:
      - iris

  grafana-oncall:
    hostname: grafana-oncall
    image: grafana/grafana-enterprise
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - iris

networks:
  iris:
    name: iris

volumes:
  grafana-storage:
